---
services:
  next-app:
    build: next-app
    restart: unless-stopped
    read_only: true
    ports:
      - 3000:3000
    volumes:
      - type: tmpfs
        target: /tmp
    depends_on:
      - db
    environment:
      NODE_ENV: production
      JWT_SECRET: FCLckdFbhwqzaSZR4guQrVTX3ZykL9wFaCScNrj4ZvspWn3FM92Csu3ugZLgavfEsucaaJjqXqCa82WnMgfEDGg9j5RURu4ZKxvkrYvmARfdadEAs38XewrVmdFENAMrXvxn7RNkFvda6SCtsbJD9jsZCAuT2pyG
      MONGODB_URI: mongodb://db:27017/slashgirlfriends
      REPORT_BOT_BASEURL: http://bot:3001
      CHAT_ENABLED: 1
  payment-processor:
    build: paymentProcessor
    restart: unless-stopped
    read_only: true
    ports:
      - 3002:3002
    volumes:
      - type: tmpfs
        target: /tmp
    depends_on:
      - next-app
    environment:
      NODE_ENV: production
      PORT: 3002
      JWT_SECRET: FCLckdFbhwqzaSZR4guQrVTX3ZykL9wFaCScNrj4ZvspWn3FM92Csu3ugZLgavfEsucaaJjqXqCa82WnMgfEDGg9j5RURu4ZKxvkrYvmARfdadEAs38XewrVmdFENAMrXvxn7RNkFvda6SCtsbJD9jsZCAuT2pyG
  bot:
    build: bot
    restart: unless-stopped
    read_only: true
    ports:
      - 3001:3001
    volumes:
      - type: tmpfs
        target: /tmp
      - type: tmpfs
        target: /root/.config
    depends_on:
      - next-app
      - payment-processor
    environment:
      NODE_ENV: production
      PORT: 3001
      SHOW_LOGS: 1
      FLAG: snakeCTF{p4y_f0r_l0v3}
      JWT_SECRET: FCLckdFbhwqzaSZR4guQrVTX3ZykL9wFaCScNrj4ZvspWn3FM92Csu3ugZLgavfEsucaaJjqXqCa82WnMgfEDGg9j5RURu4ZKxvkrYvmARfdadEAs38XewrVmdFENAMrXvxn7RNkFvda6SCtsbJD9jsZCAuT2pyG
      SITE_BASEURL: http://next-app:3000
      PAYMENT_SITE_BASEURL: http://payment-processor:3002
  db:
    image: mongo
    user: mongodb
    read_only: true
    volumes:
      - /data/db
      - /tmp
